global:
  scrape_interval: 60s
remote_write:
  - url: https://prometheus-prod-65-prod-eu-west-2.grafana.net/api/prom/push
    basic_auth:
      username: ${GRAFANA_USERNAME}
      password: ${GRAFANA_PASSWORD}
scrape_configs:
  - job_name: node
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: blooters
    static_configs:
      - targets: ["api:8080"]